# Description: This file contains the code for the VFL Robustness Analysis Experiment on Adult Dataset.
# Author: Matthew L. Merritt


## Experiment Params:

# n distinct parties 
n_distinct_parties = 5

# dataset dir (must be generated by pre-processor for respective n_distinct_parties)
dataset_dir = f"datasets/pre_processed_adult_{n_distinct_parties}p"

# results dir (where to save the results)
results_dir = f"results/adult_{n_distinct_parties}p"



## Importing Required Libraries

# Libraries for Data Handling
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader, TensorDataset

# Libraries for Algorithms
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import average_precision_score, accuracy_score
import helper

# Libraries for Data Visulation Tools
import matplotlib.pyplot as plt
import seaborn as sns








if __name__ == '__main__':

    # (n_distinct_parties, layers, noise_scales=[0.0])
    helper.generateAnalysis(n_distinct_parties, 1, [0.0])